apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  namespace: rabbitmq-system
  labels:
    app.kubernetes.io/name: rabbitmq
  annotations:
    external-dns.alpha.kubernetes.io/hostname: iferdel.dev
spec:
  ingressClassName: haproxy
  rules:
    - host: iferdel.dev
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
