apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq
  namespace: rabbitmq-system
spec:
  defaultBackend: 
    service:
      name: rabbitmq
      port:
        number: 15672
  ingressClassName: tailscale
  tls:
  - hosts:
    - rabbitmq.tailbb8712.ts.net
  rules:
    - host: rabbitmq.tailbb8712.ts.net
