apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
spec:
  service:
    type: ClusterIP
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 800m
      memory: 1Gi

  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
                - mountPath: /etc/rabbitmq/definitions.json
                  subPath: definitions.json
                  name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions
                  
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      # RabbitMQ Cluster Kubernetes Operator enabled rabbitmq_peer_discovery_k8s, rabbitmq_prometheus and rabbitmq_management by default.
    additionalConfig: |
      loopback_users.guest = false
      cluster_name = rabbitmq-overview
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
      management.listeners.ssl = false
      load_definitions = /etc/rabbitmq/definitions.json
      collect_statistics_interval = 1000

  persistence:
    storage: 0

