apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: 
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: 691b0b91-06b6-4244-8d63-c77d1b3a530f
      vaultUrl: https://iferdel-homelab-staging.vault.azure.net

      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets

