apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: 
  name: azure-kv-store
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ManagedIdentity
      identityId: 691b0b91-06b6-4244-8d63-c77d1b3a530f
      vaultUrl: https://iferdel-homelab-staging.vault.azure.net
      tenantId: ce16100c-8dcb-47a7-9964-4b46ab5962a3

      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets

