apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id:
    azure.workload.identity/client-secret:
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: 
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://iferdel-homelab-staging.vault.azure.net
      serviceAccountRef:
        name: workload-identity-sa

      # identityId: 691b0b91-06b6-4244-8d63-c77d1b3a530f
      #
      # authSecretRef:
      #   clientId:
      #     name: azure-creds
      #     key: ClientID
      #     namespace: external-secrets
      #   clientSecret:
      #     name: azure-creds
      #     key: ClientSecret
      #     namespace: external-secrets
      #
