apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: 
  name: azure-kv-store
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ServicePrincipal
      vaultUrl: https://iferdel-homelab-staging.vault.azure.net
      tenantId: 1b2dc682-313b-4925-b297-c5a0d3da9a24
      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets

