apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  interval: 5m
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 60m
      version: 4.1.1
  values: # patch https://www.talos.dev/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs/
    engines:
      local:
        lvm:
          enabled: false
        zfs: 
          enabled: false
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false

