apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 60m
      version: 4.1.0
  values: # Patches for replicated local storage with OpenEBS as per Talos docs
    engines:
      local:
        lvm:
          enabled: false
        zfs: 
          enabled: false
      replicated:
        mayastor:
          enabled: false
    # The mayastor section here only disables certain initContainers if needed,
    # but does not handle etcd or loki configuration. That's handled in the separate Mayastor HelmRelease.
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false

