apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 60m
      version: 4.1.1
