apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    
    apps:
      - type: "grafana-lokiexplore-app"
        org_id: 1
        org_name: "Grafana"
        disabled: false
        jsonData:
          apiUrl: http://localhost:3100
          isApiKeySet: true
        secureJsonData:
          apiKey: secret-key
