apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.80.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: operator-oauth
            key: oauth-client-id
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: operator-oauth
            key: oauth-client-secret
