apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.80.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
  valuesFrom:
  - kind: Secret
    name: operator-oauth
    namespace: tailscale
    valuesKey: clientId
    targetPath: oauth.clientId
  - kind: Secret
    name: operator-oauth
    namespace: tailscale
    valuesKey: clientSecret
    targetPath: oauth.clientSecret
