apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale-system
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.80.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
  values:
    oauth: {}
    oauthSecretVolume:
      secret:
        secretName: operator-oauth
    apiServerProxyConfig:
      mode: "true"
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator"
