apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.74.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  # valuesFrom:
  # - kind: Secret
  #   name: tailscale-oauth
  #   valuesKey: clientId
  #   targetPath: oauth.clientId
  # - kind: Secret
  #   name: tailscale-oauth
  #   valuesKey: clientSecret
  #   targetPath: oauth.clientSecret
