apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
spec:
  service:
    type: ClusterIP
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 800m
      memory: 1Gi

  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
                - mountPath: /etc/rabbitmq/definitions.json
                  subPath: definitions.json
                  name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions
                  
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_prometheus
    additionalConfig: |
      default_user=guest
      default_pass=guest
      loopback_users.guest = false
      listeners.tcp.default = 5672
      management.listeners.port = 15672
      management.listeners.ssl = false
      vm_memory_high_watermark = 768MiB
      cluster_name = rabbitmq-overview
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
      cluster_formation.classic_config.nodes.1 = rabbit@iot-rabbitmq
      load_definitions = /etc/rabbitmq/definitions.json
      collect_statistics_interval = 1000

  persistence:
    storage: 0

