# storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-1
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
