apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-identity-webhook
  namespace: azure-workload-identity-system
spec:
  chart:
    spec:
      chart: workload-identity-webhook
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
      version: "x.x.x"
  values:
    azureTenantID: ce16100c-8dcb-47a7-9964-4b46ab5962a3
