apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azure-workload-identity
  namespace: azure-workload-identity-system
spec:
  interval: 1h
  url: https://azure.github.io/azure-workload-identity/charts
