---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: infrastructure-controllers
 namespace: flux-system
spec:
 interval: 1h
 retryInterval: 2m
 timeout: 10m
 prune: true
 wait: true
 sourceRef:
   kind: GitRepository
   name: flux-system
 path: ./infrastructure/controllers/staging
---
