apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iot-logs-pvc
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
