apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: haproxy-controller
spec:
  interval: 24h
  chart:
    spec:
      chart: kubernetes-ingress
      version: "1.44.x"
      sourceRef:
        kind: HelmRepository
        name: haproxy
  values:
    controller:
      service:
        type: NodePort

