apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: iot-api
      http:
        paths:
          - path: /
            pathType: Prefix
            backedn:
              service:
                name: iot-api
                port:
                  number: 80
