apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: mayastor
spec:
  timeout: 5m
  releaseName: mayastor
  interval: 5m
  chart:
    spec:
      chart: mayastor
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
      version: 2.4.0
  values:
    etcd:
      localpvScConfig:
        basePath: "/var/openebs/local/mayastor/etcd"
    loki-stack:
      localpvScConfig:
        basePath: "/var/openebs/local/mayastor/loki"

