apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-simulation
  template:
    metadata:
      labels:
        app: iot-sensor-simulation
        policy-type: "app"
    spec:
      containers:
        - name: iot-sensor-simulation
          image: iferdel777/iot-sensor-simulation:v1.0.1

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: RABBIT_CONN_STRING 
              valueFrom:
                configMapKeyRef:
                  name: iot
                  key: RABBIT_CONN_STRING
          envFrom:
            - secretRef:
                name: iot-sensor-simulation-env

      restartPolicy: Always
