apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-simulation
  template:
    metadata:
      labels:
        app: iot-sensor-simulation
        policy-type: "app"
    spec:
      containers:
        - name: iot-sensor-simulation
          image: iferdel777/iot-sensor-simulation:v1.0.1

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: iot-sensor-simulation-configmap
          env:
            - name: POSTGRES_CONN_STRING
              valueFrom:
                secretKeyRef:
                  namespace: data
                  name: timescaledb-conn-string
                  key: POSTGRES_CONN_STRING

      restartPolicy: Always
