apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iot-sensor-simulation-env
  namespace: iot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data: 
    - secretKey: RABBIT_CONN_STRING
      remoteRef:
        key: iot-rabbitmq-conn-string
    - secretKey: POSTGRES_CONN_STRING
      remoteRef:
        key: iot-postgres-conn-string
---

