apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iot-sensor-simulation
  namespace: iot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data: 
    - secretKey: SENSOR_SERIAL_NUMBER
      remoteRef:
        key: iot-sensor-simulation-serial-number
    - secretKey: SENSOR_SAMPLE_FREQUENCY
      remoteRef:
        key: iot-sensor-simulation-sample-frequency
    - secretKey: 
