apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "0.11.x"
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
