apiVersion: v1
kind: Namespace
metadata:
  name: iferdel
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     app.kubernetes.io/component: monitoring
#     pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: iot
---
