---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-monitoring-init-script
  namespace: data
data:
  monitoring-init.sql: |
    -- * Activate the pg_stat_statements extension
    CREATE EXTENSION pg_stat_statements;

    -- * Activate the pg_stat_kcache extension
    CREATE EXTENSION pg_stat_kcache;

