resources:
  - ../../base/timescaledb/
  - pvc.yaml
patches:
  - target:
      kind: Cluster
      name: timescaledb
    patch: |-
      - op: add
        path: /spec/volumes
        value:
          persistentVolumeClaim:
            claimName: timescaledb-pvc
