resources:
  - ../../base/timescaledb/
  - configmap.yaml
  - secrets.yaml
patches:
  - target:
      kind: Cluster
      name: timescaledb
    patch: |-
      - op: add
        path: /spec
        value:

          ephemeralVolumeSource:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: "longhorn"
                resources:
                  requests:
                    storage: 1Gi

          managed:
            roles:
              - name: iot
                ensure: present
                comment: superuser-like role
                login: true
                superuser: false
                inherit: true
                inRoles:
                  - pg_read_all_data
                  - pg_write_all_data
                  - pg_maintain 
                  - pg_signal_backend 
                  - pg_monitor 
                  - pg_use_reserved_connections
                passwordSecret:
                  name: cluster-roles-iot

              - name: iot_app
                ensure: present
                comment: role dedicated to be used by iot service
                login: true
                superuser: false
                createdb: true
                inherit: true
                passwordSecret:
                  name: cluster-roles-iot-app

              - name: iot_monitoring
                ensure: present
                comment: role dedicated to be used to access monitoring parameters from pg_stat_statements and thus visualize them in a tool such as grafana
                login: true
                superuser: false
                inherit: true
                inRoles:
                  - pg_monitor 
                passwordSecret:
                  name: cluster-roles-iot-monitoring

              - name: iot_readonly
                ensure: present
                comment: readonly role (used in visualization tools or for etl processes)
                login: true
                superuser: false
                inherit: true
                inRoles:
                  - pg_read_all_data
                  - pg_read_all_stats
                disablePassword: true

              - name: iot_replication
                ensure: present
                comment: replication role
                login: true
                superuser: false
                inherit: true
                passwordSecret:
                  name: cluster-roles-iot-replication

          bootstrap:
            initdb:
              postInitApplicationSQLRefs:
                configMapRefs:
                - name: timescaledb-init-script
                  key: init.sql
