resources:
  - ../../base/timescaledb/
  - configmap.yaml
  - secrets.yaml
patches:
  - target:
      kind: Cluster
      name: timescaledb
    patch: |-
      - op: add
        path: /spec
        value:

          storage:
            storageClass: longhorn
            size: 5Gi

