resources:
  - ../../base/timescaledb/
  - configmap.yaml
patches:
  - target:
      kind: Cluster
      name: timescaledb
    patch: |-
      - op: add
        path: /spec
        value:
          storage:
            storageClass: longhorn
            size: 5Gi
          bootstrap:
            initdb:
              customScripts:
                fromConfigMap:
                  name: timescaledb-init-script
          podTemplate:
            containers:
              - name: postgres
                env:
                  - name: IOT_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: timescaledb-roles
                        key: IOT_PASSWORD
                  - name: IOT_REPLICATION_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: timescaledb-roles
                        key: IOT_REPLICATION_PASSWORD
                  - name: IOT_MONITORING_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: timescaledb-roles
                        key: IOT_MONITORING_PASSWORD
                  - name: IOT_APP_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: timescaledb-roles
                        key: IOT_APP_PASSWORD
                  - name: IOT_READONLY_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: timescaledb-roles
                        key: IOT_READONLY_PASSWORD
