resources:
  - ../../base/timescaledb/
patches:
  - target:
      kind: Cluster
      name: timescaledb
    patch: |-
      - op: add
        path: /spec
        value:
          storage:
            size: 5Gi
